---
output:
  md_document:
    variant: gfm
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)

set.seed(1)
```

minilocate
------------------------------------------------------------------------------

The goal of minilocate is to provide a way to search for a vector within another
vector i.e. to find a needle in a haystack.

As far as I know, there's no base function for finding one sequence inside 
another sequence.

The core code was originally written by [Jonathan Carroll](https://twitter.com/carroll_jono)
in a response to [this post](https://coolbutuseless.github.io/2018/04/03/finding-a-length-n-needle-in-a-haystack/).

I've adapted the code to suit my needs:

* Support for the `bit` class from the `bit` package.
* Support for aligned searches


Examples
------------------------------------------------------------------------------


```{r example}
locate(c('m', 'n'), letters)
locate(c(0, 0, 1), sample(c(0, 1), 100, replace=TRUE))
locate(c(T, F, F), c(T, F, F, T, F, T, F, F))
locate(as.raw(10:11), 1:100)
locate(c('5', '6'), 1:10)
locate(c(0, 1), c(0, 0, 1, 0, 0, 1), alignment = 2)
```
